fix: use url instead of hostname when caching headers and cookies
tlsnotary/tlsn-extension pull request #123
Opened 2024-12-11 09:08 UTC by 0xtsukino

Instead of using hostname when retrieving headers and cookies for plugin, this PR changes it so that it's using url without query params instead (e.g. `https://example.com/x?hello=world` would be `https://example.com/x`). This allows more precise headers to be cached and retrieved, and will fix the twitter plugin issue where incorrect auth tokens are used.

2025-01-07 10:18 UTC, heeckhau approved these changes

2025-01-08 19:22 UTC, Codetrauma approved these changes

2025-01-09 04:33 UTC, Codetrauma requested changes
Need to implement getting cookies/headers to work with wildcards in URL's

2025-01-16 14:17 UTC, heeckhau commented on src/entries/Background/db.ts
> +  for await (const [key, value] of headersDb.sublevel(headerLink).iterator()) {
![image](https://github.com/user-attachments/assets/f747cd1a-497b-4953-8c02-33ca02c8ca7c)

2025-01-20 18:09 UTC, 0xtsukino commented
Can i merge this @heeckhau @Codetrauma ?

2025-01-20 18:23 UTC, Codetrauma commented
> Can i merge this @heeckhau @Codetrauma ?

I'm double checking the error that @heeckhau posted now

2025-01-20 18:57 UTC, Codetrauma approved these changes

2025-01-21 10:00 UTC, merged